[package]
name = "rust_lib"
version = "0.1.0"
authors = ["Wojciech Kozlowski <wk@wojciechkozlowski.eu>",
           "Marco Lam <cylammarco@gmail.com"]

[dependencies]
serde = "1.0.0"
serde_derive = "1.0.0"
bincode = "1.0.0"
